---
- name: Install PHP packages
  yum: name={{ item }} state=installed
  with_items:
    - php70u
    - php70u-pdo
    - php70u-mysqlnd
    - php70u-opcache
    - php70u-xml
    - php70u-mcrypt
    - php70u-gd
    - php70u-devel
    - php70u-intl
    - php70u-mbstring
    - php70u-json
    - php70u-iconv

- name: Copy PHP Configuration File
  template: src=php.ini dest=/etc/php.ini

- name: Create Log Directory For PHP and Give It "Apache" user ownership
  file: path=/var/log/php state=directory owner=apache

- name: Install Composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer creates=/usr/bin/composer
